/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppJoinRouteImport } from './routes/app/join'
import { Route as AppNearbyRouteImport } from './routes/app/nearby'
import { Route as AppPlayRouteImport } from './routes/app/play'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppRankingRouteImport } from './routes/app/ranking'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppGameCodeRouteImport } from './routes/app/game.$code'
import { Route as AppHistoryIdRouteImport } from './routes/app/history.$id'
import { Route as AppRoomCodeRouteImport } from './routes/app/room.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRoute,
} as any)
const AppNearbyRoute = AppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGameCodeRoute = AppGameCodeRouteImport.update({
  id: '/game/$code',
  path: '/game/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIdRoute = AppHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppRoomCodeRoute = AppRoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/create': typeof AppCreateRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/join': typeof AppJoinRoute
  '/app/nearby': typeof AppNearbyRoute
  '/app/play': typeof AppPlayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/settings': typeof AppSettingsRoute
  '/join/$code': typeof JoinCodeRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/game/$code': typeof AppGameCodeRoute
  '/app/history/$id': typeof AppHistoryIdRoute
  '/app/room/$code': typeof AppRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/create': typeof AppCreateRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/join': typeof AppJoinRoute
  '/app/nearby': typeof AppNearbyRoute
  '/app/play': typeof AppPlayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/settings': typeof AppSettingsRoute
  '/join/$code': typeof JoinCodeRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/game/$code': typeof AppGameCodeRoute
  '/app/history/$id': typeof AppHistoryIdRoute
  '/app/room/$code': typeof AppRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/create': typeof AppCreateRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/join': typeof AppJoinRoute
  '/app/nearby': typeof AppNearbyRoute
  '/app/play': typeof AppPlayRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/settings': typeof AppSettingsRoute
  '/join/$code': typeof JoinCodeRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/game/$code': typeof AppGameCodeRoute
  '/app/history/$id': typeof AppHistoryIdRoute
  '/app/room/$code': typeof AppRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/create'
    | '/app/friends'
    | '/app/history'
    | '/app/join'
    | '/app/nearby'
    | '/app/play'
    | '/app/profile'
    | '/app/ranking'
    | '/app/settings'
    | '/join/$code'
    | '/app/'
    | '/api/auth/$'
    | '/app/game/$code'
    | '/app/history/$id'
    | '/app/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/create'
    | '/app/friends'
    | '/app/history'
    | '/app/join'
    | '/app/nearby'
    | '/app/play'
    | '/app/profile'
    | '/app/ranking'
    | '/app/settings'
    | '/join/$code'
    | '/app'
    | '/api/auth/$'
    | '/app/game/$code'
    | '/app/history/$id'
    | '/app/room/$code'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/create'
    | '/app/friends'
    | '/app/history'
    | '/app/join'
    | '/app/nearby'
    | '/app/play'
    | '/app/profile'
    | '/app/ranking'
    | '/app/settings'
    | '/join/$code'
    | '/app/'
    | '/api/auth/$'
    | '/app/game/$code'
    | '/app/history/$id'
    | '/app/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/join': {
      id: '/app/join'
      path: '/join'
      fullPath: '/app/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nearby': {
      id: '/app/nearby'
      path: '/nearby'
      fullPath: '/app/nearby'
      preLoaderRoute: typeof AppNearbyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play': {
      id: '/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/game/$code': {
      id: '/app/game/$code'
      path: '/game/$code'
      fullPath: '/app/game/$code'
      preLoaderRoute: typeof AppGameCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history/$id': {
      id: '/app/history/$id'
      path: '/$id'
      fullPath: '/app/history/$id'
      preLoaderRoute: typeof AppHistoryIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/app/room/$code': {
      id: '/app/room/$code'
      path: '/room/$code'
      fullPath: '/app/room/$code'
      preLoaderRoute: typeof AppRoomCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryIdRoute: typeof AppHistoryIdRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryIdRoute: AppHistoryIdRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppJoinRoute: typeof AppJoinRoute
  AppNearbyRoute: typeof AppNearbyRoute
  AppPlayRoute: typeof AppPlayRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRankingRoute: typeof AppRankingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGameCodeRoute: typeof AppGameCodeRoute
  AppRoomCodeRoute: typeof AppRoomCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppJoinRoute: AppJoinRoute,
  AppNearbyRoute: AppNearbyRoute,
  AppPlayRoute: AppPlayRoute,
  AppProfileRoute: AppProfileRoute,
  AppRankingRoute: AppRankingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGameCodeRoute: AppGameCodeRoute,
  AppRoomCodeRoute: AppRoomCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
