import 'dart:async';
import 'package:app_links/app_links.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:nearby_connections/nearby_connections.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:share_plus/share_plus.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const url=String.fromEnvironment('SUPABASE_URL',defaultValue:'');
const key=String.fromEnvironment('SUPABASE_ANON_KEY',defaultValue:'');
SupabaseClient? get supabase=>url.isEmpty||key.isEmpty?null:Supabase.instance.client;
const cats=['Nome','Apelido','Animal','País','Cidade','Comida','Bebida','Profissão','Objeto','Marca','Filme','Série','Jogo','Personagem','Desporto','Clube','Celebridade','Planta','Corpo humano','Tecnologia','Aplicação','Veículo'];
const alpha='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
final nav=GlobalKey<NavigatorState>();

Future<void> main()async{
 WidgetsFlutterBinding.ensureInitialized();
 if(url.isNotEmpty&&key.isNotEmpty)await Supabase.initialize(url:url,anonKey:key,realtimeClientOptions:const RealtimeClientOptions(eventsPerSecond:20));
 runApp(const ProviderScope(child:StopApp()));
}
ThemeData appTheme(Brightness b){final d=b==Brightness.dark;final cs=ColorScheme.fromSeed(seedColor:const Color(0xFFE52D32),brightness:b);return ThemeData(useMaterial3:true,colorScheme:cs,scaffoldBackgroundColor:d?const Color(0xff090a0d):const Color(0xfff6f5f2),cardTheme:CardThemeData(color:d?const Color(0xff15171c):Colors.white,elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22))),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:d?const Color(0xff101217):const Color(0xffeeeeeb),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none)));}
class StopApp extends StatefulWidget{const StopApp({super.key});@override State<StopApp> createState()=>_StopAppState();}
class _StopAppState extends State<StopApp>{ThemeMode mode=ThemeMode.dark;StreamSubscription<Uri>? links;
 @override void initState(){super.initState();final a=AppLinks();a.getInitialLink().then(open);links=a.uriLinkStream.listen(open);}
 void open(Uri u){if(u.pathSegments.isNotEmpty){final c=u.pathSegments.last;if(c.isNotEmpty)WidgetsBinding.instance.addPostFrameCallback((_)=>nav.currentState?.push(MaterialPageRoute(builder:(_)=>JoinPage(code:c.toUpperCase()))));}}
 @override void dispose(){links?.cancel();super.dispose();}
 @override Widget build(BuildContext c)=>MaterialApp(navigatorKey:nav,title:'STOP',debugShowCheckedModeBanner:false,theme:appTheme(Brightness.light),darkTheme:appTheme(Brightness.dark),themeMode:mode,home:AuthGate(themeMode:(x)=>setState(()=>mode=x)));}
class AuthGate extends StatelessWidget{final ValueChanged<ThemeMode> themeMode;const AuthGate({super.key,required this.themeMode});
 @override Widget build(BuildContext c){if(supabase==null)return Login(themeMode:themeMode,guest:true);return StreamBuilder<AuthState>(stream:supabase!.auth.onAuthStateChange,initialData:AuthState(AuthChangeEvent.initialSession,supabase!.auth.currentSession),builder:(c,s)=>s.data?.session==null?Login(themeMode:themeMode,guest:false):Home(themeMode:themeMode));}}
class Login extends StatefulWidget{final ValueChanged<ThemeMode> themeMode;final bool guest;const Login({super.key,required this.themeMode,required this.guest});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final email=TextEditingController(),pass=TextEditingController(),user=TextEditingController();bool create=false;
 Future<void> go()async{if(supabase==null){Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(themeMode:widget.themeMode,guest:true)));return;}try{if(create){if(user.text.trim().length<3)throw Exception('Username demasiado curto');await supabase!.auth.signUp(email:email.text.trim(),password:pass.text,data:{'username':user.text.trim()});}else{await supabase!.auth.signInWithPassword(email:email.text.trim(),password:pass.text);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
 @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:440),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.stop_circle_rounded,size:90,color:Color(0xffe52d32)),const Text('STOP',textAlign:TextAlign.center,style:TextStyle(fontSize:64,fontWeight:FontWeight.w900,letterSpacing:-5)),const Text('Joga. Pensa. Para!',textAlign:TextAlign.center),const SizedBox(height:32),if(widget.guest)const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('Modo convidado. Configura o Supabase para multiplayer real.'))),if(create)TextField(controller:user,decoration:const InputDecoration(labelText:'Username')),if(create)const SizedBox(height:10),TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:10),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Password')),const SizedBox(height:14),FilledButton(onPressed:go,child:Padding(padding:const EdgeInsets.all(14),child:Text(create?'Criar conta':'Entrar'))),TextButton(onPressed:()=>setState(()=>create=!create),child:Text(create?'Já tenho conta':'Criar conta')),if(!create)TextButton(onPressed:()=>Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(themeMode:widget.themeMode,guest:true))),child:const Text('Jogar como convidado'))])))));}}
class Home extends StatefulWidget{final ValueChanged<ThemeMode> themeMode;final bool guest;const Home({super.key,required this.themeMode,this.guest=false});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0;String name='Jogador';@override void initState(){super.initState();load();}
 Future<void> load()async{if(supabase==null)return;final u=supabase!.auth.currentUser;if(u==null)return;final p=await supabase!.from('profiles').select('username').eq('id',u.id).maybeSingle();if(mounted&&p!=null)setState(()=>name=p['username']??'Jogador');}
 @override Widget build(BuildContext c){final body=[Dashboard(name:name),const Ranking(),Profile(name:name)];return Scaffold(body:SafeArea(child:body[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(x)=>setState(()=>tab=x),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Início'),NavigationDestination(icon:Icon(Icons.emoji_events_outlined),selectedIcon:Icon(Icons.emoji_events),label:'Ranking'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Perfil')]));}}
class Dashboard extends StatelessWidget{final String name;const Dashboard({super.key,required this.name});
 Widget action(BuildContext c,String t,String s,IconData i,VoidCallback f,bool p)=>Card(color:p?Theme.of(c).colorScheme.primaryContainer:null,child:InkWell(onTap:f,borderRadius:BorderRadius.circular(22),child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[Icon(i,size:34),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800)),Text(s)])),const Icon(Icons.chevron_right)]))));
 @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[Row(children:[const CircleAvatar(child:Icon(Icons.person)),const SizedBox(width:10),Expanded(child:Text('Olá, '+name,style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold))),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Settings())),icon:const Icon(Icons.settings_outlined))]),const SizedBox(height:26),const Text('Jogar',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:14),action(c,'Criar partida','Mínimo 8 categorias, letras e tempo.',Icons.add_circle,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Create())),true),const SizedBox(height:10),action(c,'Entrar numa partida','Código ou link de convite.',Icons.login,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const JoinEntry())),false),const SizedBox(height:10),action(c,'Jogadores próximos','Nearby Connections, sem distância GPS.',Icons.wifi_tethering,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const NearbyPage())),false),const SizedBox(height:18),action(c,'Histórico','Resultados e partidas anteriores.',Icons.history,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const History())),false),]);}
class Create extends StatefulWidget{const Create({super.key});@override State<Create> createState()=>_CreateState();}
class _CreateState extends State<Create>{final chosenCats=<String>{...cats.take(8)},chosenLetters=<String>{...alpha};int seconds=60,rounds=5,maxPlayers=8;String mode='Privado';final custom=TextEditingController();
 String code(){const x='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';var n=DateTime.now().microsecondsSinceEpoch;return List.generate(6,(_){final z=x[n%x.length];n~/=x.length;return z;}).join();}
 Future<void> create()async{if(chosenCats.length<8)return msg('São necessárias pelo menos 8 categorias.');if(chosenLetters.isEmpty)return msg('Seleciona pelo menos uma letra.');if(supabase==null)return Navigator.push(context,MaterialPageRoute(builder:(_)=>LocalRoom(code:code())));try{final r=await supabase!.from('rooms').insert({'code':code(),'host_id':supabase!.auth.currentUser!.id,'visibility':mode.toLowerCase(),'max_players':maxPlayers,'categories':chosenCats.toList(),'letters':chosenLetters.toList(),'round_seconds':seconds,'total_rounds':rounds}).select('id,code').single();await supabase!.from('room_players').insert({'room_id':r['id'],'user_id':supabase!.auth.currentUser!.id,'is_host':true});if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>Lobby(id:r['id'],code:r['code'])));}catch(e){msg(e.toString());}}
 void msg(String x)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Criar partida')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Jogadores',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:6,children:[2,3,4,5,6,7,8].map((x)=>ChoiceChip(label:Text('$x+'),selected:maxPlayers==x,onSelected:(_)=>setState(()=>maxPlayers=x))).toList()),const SizedBox(height:15),const Text('Modo',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:6,children:['Público','Privado','Apenas amigos'].map((x)=>ChoiceChip(label:Text(x),selected:mode==x,onSelected:(_)=>setState(()=>mode=x))).toList()),const SizedBox(height:15),Text('Categorias ('+chosenCats.length.toString()+'/8 mínimo)',style:const TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:6,runSpacing:6,children:cats.map((x)=>FilterChip(label:Text(x),selected:chosenCats.contains(x),onSelected:(v)=>setState(()=>v?chosenCats.add(x):chosenCats.remove(x))).toList()),Row(children:[Expanded(child:TextField(controller:custom,decoration:const InputDecoration(labelText:'Categoria personalizada'))),IconButton(onPressed:(){if(custom.text.trim().isNotEmpty)setState((){chosenCats.add(custom.text.trim());custom.clear();});},icon:const Icon(Icons.add))]),const SizedBox(height:12),const Text('Letras',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:5,children:alpha.map((x)=>FilterChip(label:Text(x),selected:chosenLetters.contains(x),onSelected:(v)=>setState(()=>v?chosenLetters.add(x):chosenLetters.remove(x))).toList()),Row(children:[TextButton(onPressed:()=>setState(()=>chosenLetters.addAll(alpha)),child:const Text('Selecionar todas')),TextButton(onPressed:()=>setState(()=>chosenLetters.clear()),child:const Text('Limpar'))]),const SizedBox(height:12),const Text('Tempo por ronda',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:5,children:[15,30,45,60,90,120].map((x)=>ChoiceChip(label:Text(x.toString()+'s'),selected:seconds==x,onSelected:(_)=>setState(()=>seconds=x))).toList()),Row(children:[const Text('Rondas'),const Spacer(),DropdownButton<int>(value:rounds,items:[1,3,5,7,10,15,20].map((x)=>DropdownMenuItem(value:x,child:Text(x.toString()))).toList(),onChanged:(x)=>setState(()=>rounds=x!))]),const SizedBox(height:12),FilledButton(onPressed:create,child:const Padding(padding:EdgeInsets.all(14),child:Text('CRIAR SALA')))]));}}
class JoinEntry extends StatelessWidget{const JoinEntry({super.key});@override Widget build(BuildContext c){final t=TextEditingController();return Scaffold(appBar:AppBar(title:const Text('Entrar numa partida')),body:Padding(padding:const EdgeInsets.all(20),child:Column(children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Código da sala')),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>JoinPage(code:t.text.trim().toUpperCase()))),child:const Text('ENTRAR'))]));}}
class JoinPage extends StatelessWidget{final String code;const JoinPage({super.key,required this.code});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Convite STOP')),body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.group_add,size:70,color:Color(0xffe52d32)),Text('Sala '+code,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:12),FilledButton(onPressed:()async{if(supabase==null)return Navigator.pop(c);try{final r=await supabase!.from('rooms').select('id,code').eq('code',code).single();await supabase!.from('room_players').insert({'room_id':r['id'],'user_id':supabase!.auth.currentUser!.id});if(c.mounted)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>Lobby(id:r['id'],code:code)));}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString())));}},child:const Text('ENTRAR NA SALA'))])));}
class Lobby extends StatefulWidget{final String id,code;const Lobby({super.key,required this.id,required this.code});@override State<Lobby> createState()=>_LobbyState();}
class _LobbyState extends State<Lobby>{List<Map<String,dynamic>> players=[];StreamSubscription? stream;@override void initState(){super.initState();load();stream=supabase!.from('room_players').stream(primaryKey:['id']).eq('room_id',widget.id).listen((_)=>load());}Future<void>load()async{final x=await supabase!.from('room_players').select('id,is_host,profiles(username)').eq('room_id',widget.id);if(mounted)setState(()=>players=List<Map<String,dynamic>>.from(x));}@override void dispose(){stream?.cancel();super.dispose();}Future<void>share()async{final link='stop://join/'+widget.code;await SharePlus.instance.share(ShareParams(text:'Entra na minha partida de STOP! '+link));}Future<void>start()async{try{final r=await supabase!.rpc('start_game',params:{'p_room_id':widget.id});if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>Game(roundId:r['round_id'])));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Lobby')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Text('SALA',style:TextStyle(letterSpacing:3)),Text(widget.code,style:const TextStyle(fontSize:42,fontWeight:FontWeight.w900)),OutlinedButton(onPressed:share,child:const Text('Partilhar convite'))]))),Card(child:Column(children:[ListTile(title:Text('Jogadores ('+players.length.toString()+')')), ...players.map((p)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text((p['profiles'] as Map?)?['username']??'Jogador'),trailing:p['is_host']==true?const Chip(label:Text('HOST')):null))])),if(players.length>=2)FilledButton(onPressed:start,child:const Text('COMEÇAR PARTIDA'))]));}}
class Game extends StatefulWidget{final String roundId;const Game({super.key,required this.roundId});@override State<Game> createState()=>_GameState();}
class _GameState extends State<Game>{Map<String,dynamic>? r;final ans=<String,String>{};Timer? timer;int left=0;@override void initState(){super.initState();load();}Future<void>load()async{r=await supabase!.from('rounds').select().eq('id',widget.roundId).single();final end=DateTime.parse(r!['ends_at']);timer=Timer.periodic(const Duration(milliseconds:500),(_){final n=end.difference(DateTime.now()).inSeconds.clamp(0,999);if(mounted)setState(()=>left=n);if(n==0){timer?.cancel();stop(true);}});setState((){});}Future<void>stop(bool auto)async{for(final e in ans.entries)await supabase!.from('answers').upsert({'round_id':widget.roundId,'user_id':supabase!.auth.currentUser!.id,'category':e.key,'answer':e.value});await supabase!.rpc('stop_round',params:{'p_round_id':widget.roundId,'p_reason':auto?'timeout':'manual'});if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Verify(roundId:widget.roundId)));}@override void dispose(){timer?.cancel();super.dispose();}@override Widget build(BuildContext c){if(r==null)return const Scaffold(body:Center(child:CircularProgressIndicator()));final cs=List<String>.from(r!['categories']);return Scaffold(appBar:AppBar(title:Text('Ronda '+r!['round_number'].toString())),body:ListView(padding:const EdgeInsets.all(18),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(r!['letter'],style:const TextStyle(fontSize:60,fontWeight:FontWeight.w900)),Text(left.toString().padLeft(2,'0'),style:TextStyle(fontSize:45,fontWeight:FontWeight.w900,color:left<=10?Theme.of(c).colorScheme.error:null))]),...cs.map((x)=>Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(onChanged:(v)=>ans[x]=v,decoration:InputDecoration(labelText:x)))),FilledButton.icon(onPressed:()=>stop(false),icon:const Icon(Icons.stop_circle),label:const Text('STOP!'))]));}}
class Verify extends StatefulWidget{final String roundId;const Verify({super.key,required this.roundId});@override State<Verify> createState()=>_VerifyState();}
class _VerifyState extends State<Verify>{List<Map<String,dynamic>> rows=[];@override void initState(){super.initState();load();}Future<void>load()async{final x=await supabase!.from('answers').select('*,profiles(username)').eq('round_id',widget.roundId);setState(()=>rows=List<Map<String,dynamic>>.from(x));}Future<void>finish()async{await supabase!.rpc('finalize_round',params:{'p_round_id':widget.roundId});if(mounted)Navigator.popUntil(context,(r)=>r.isFirst);}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Verificação')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Respostas',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),...rows.map((x)=>Card(child:ListTile(title:Text(x['category'].toString()+' · '+(x['answer']??'—').toString()),subtitle:Text((x['profiles'] as Map?)?['username']??'Jogador'),trailing:Text(x['validity']=='valid'?'10 pts':x['validity']=='invalid'?'0 pts':'Rever')))),FilledButton(onPressed:finish,child:const Text('CALCULAR RESULTADOS'))]));}}
class Ranking extends StatelessWidget{const Ranking({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Ranking')),body:supabase==null?const Center(child:Text('Configura o Supabase para ranking online.')):FutureBuilder(future:supabase!.from('profiles').select('username,total_points,wins').order('total_points',ascending:false).limit(50),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final x=s.data as List;return ListView(children:[for(int i=0;i<x.length;i++)Card(child:ListTile(leading:Text('#'+(i+1).toString()),title:Text(x[i]['username']),subtitle:Text((x[i]['wins']??0).toString()+' vitórias'),trailing:Text((x[i]['total_points']??0).toString()+' pts')))]);});}}
class Profile extends StatelessWidget{final String name;const Profile({super.key,required this.name});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const CircleAvatar(radius:44,child:Icon(Icons.person,size:44)),const SizedBox(height:12),Text(name,textAlign:TextAlign.center,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Card(child:ListTile(title:Text('Estatísticas'),subtitle:Text('Vitórias · partidas · pontos · melhor ronda'))),if(supabase!=null)FilledButton.tonal(onPressed:()=>supabase!.auth.signOut(),child:const Text('Terminar sessão'))]);}
class History extends StatelessWidget{const History({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Histórico')),body:supabase==null?const Center(child:Text('Configura o Supabase para histórico.')):FutureBuilder(future:supabase!.from('game_history').select().order('created_at',ascending:false).limit(50),builder:(c,s)=>!s.hasData?const Center(child:CircularProgressIndicator()):ListView(children:[for(final x in s.data as List)ListTile(title:Text(x['room_code']??'Partida'),subtitle:Text(x['created_at']??''),trailing:Text((x['score']??0).toString()+' pts'))]));}}
class NearbyPage extends StatefulWidget{const NearbyPage({super.key});@override State<NearbyPage> createState()=>_NearbyState();}
class _NearbyState extends State<NearbyPage>{final n=Nearby();final peers=<String,String>{};bool running=false;Future<void>scan()async{try{await Permission.bluetoothScan.request();await Permission.bluetoothConnect.request();await Permission.bluetoothAdvertise.request();await Permission.nearbyWifiDevices.request();setState(()=>running=true);await n.startDiscovery('STOP Player',Strategy.P2P_CLUSTER,onEndpointFound:(id,name,service){if(service=='com.gabriel.stop')setState(()=>peers[id]=name);},onEndpointLost:(id)=>setState(()=>peers.remove(id)),serviceId:'com.gabriel.stop');}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Nearby indisponível: '+e.toString())));}}@override void dispose(){n.stopDiscovery();super.dispose();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Jogadores próximos')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Descobre dispositivos próximos com Nearby Connections. Não é usada uma distância GPS.',style:TextStyle(fontSize:16)),const SizedBox(height:16),FilledButton(onPressed:running?null:scan,child:Text(running?'A procurar...':'PROCURAR JOGADORES')),for(final p in peers.entries)Card(child:ListTile(title:Text(p.value),subtitle:const Text('Disponível para jogar'),trailing:FilledButton(onPressed:()async{await n.requestConnection('STOP Player',p.key,onConnectionInitiated:(id,info)=>n.acceptConnection(id,onPayLoadRecieved:(a,b){}),onConnectionResult:(id,s){},onDisconnected:(id){});},child:const Text('Convidar'))))]));}}
class Settings extends StatelessWidget{const Settings({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Definições')),body:const ListView(children:[ListTile(title:Text('Tema'),subtitle:Text('Material 3 · Claro / Escuro / Sistema')),ListTile(title:Text('Privacidade'),subtitle:Text('Nearby Connections é usado para deteção próxima; não calculamos distância GPS.'))]));}}
class LocalRoom extends StatelessWidget{final String code;const LocalRoom({super.key,required this.code});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Modo convidado')),body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.offline_bolt,size:72),Text('Sala '+code,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:10),const Text('Configura o Supabase para partidas reais entre dispositivos.'),const SizedBox(height:24),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('VOLTAR'))]))));}
